### ISSUE TITLE
'place' feature

### ISSUE THREAD

**Issue by ren-03** [codeworks-data/mvp-horse-racing-prediction#2]
Hi, first and foremost, thank you for the medium article. It has helped me get started with a horse-racing prediction model

https://github.com/codeworks-data/mvp-horse-racing-prediction/blob/37bc6658194d566d57441a7bf2b4cb534a46bd2c/extract_features.py#L90

I have a question regarding your code. From what I understand (on the line above), this 'place' feature is a boolean to track if the horse finished within top 3 in the current race. Wouldn't this potentially be looking forward on the data if included in the dataset?

**Comment by IdrissaN** [comment]
Thanks for your feedback. You are right (**place** is a boolean).
The only feature in the dataset about the final results of the race is the **result** column.
Since we wanted to train different models (classification), we create the win and place features as our labels.

**Comment by ren-03** [comment]
Thank you for the reply.
I understand now, thanks!
